authapp/urls.py
from django.urls import path
from .views import home, login, register

app_name = "authapp"
urlpatterns = [
    path("", home, name="home"),
    path("login/", login, name="login"),
    path("register/", register, name="register")
]

authproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("authapp.urls"))
]

authapp/models.py
from django.db import models

# Create your models here.

authapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout


def home(request):
    return render(request, "index.html")


def login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(request, username=username, password=password)
        if user:
            login(user)
            return redirect("authapp:home")
        messages.error(request, "invalid username and password")
        return redirect("authapp:login")

    return render(request, "login.html")


def register(request):
    return render(request, "register.html")

templates/index.html
<html>
   <body>
        <ul>
            <li><a href="{% url 'authapp:login' %}">login</a></li>
            <li><a href="{% url 'authapp:register' %}">Register</a></li>
            <li><a href="/logout">logout</a></li>
        </ul>
        <h1>welcome to our authentication app</h1>
   </body> 
</html>

templates/login.html
<html>
    <body>
        <form method="post" action="#">
            <label>username</label>
            <input type="text" name="username"/>
            <br>
            <label>password</label>
            <input type="password" name="password"/>
            <br>
            <input type="submit" name="login"/>
        </form>
    </body>
</html>

templates/register.html
<html>
    <body>
        <h1>Register an account</h1>
        <form method="post" action="#">
            <label>username</label>
            <input type="text" name="username"/>
            <br>
            <label>password</label>
            <input type="password" name="password"/>
            <br>
            <label>confirm password</label>
            <input type="password" name="password2"/>
            <br>
            <input type="submit" name="register"/>
        </form>
    </body>
</html>